name: Deploy docs to Netlify
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run docs:build
        env:
          NODE_ENV: production

      - name: Deploy to Netlify
        run: |
          netlify deploy \
            --dir=./docs/.vitepress/dist \
            --prod --message="Production deploy from ${{ github.sha }}" \
            --site ${{ secrets.NETLIFY_SITE_ID }}
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
