name: Deploy docs to Netlify
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: |
          npm ci
          npm install netlify-cli -g

      - name: Build
        run: npm run docs:build
        env:
          NODE_ENV: production

      - name: Deploy to Netlify
        run: netlify deploy --dir=./.vitepress/dist --prod --message="Production deploy from ${{ github.sha }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
